package wpbn.pgis.entity;

import java.util.Date;

public class Student {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.ID
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.FNAME
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	private String fname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.LNAME
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	private String lname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.OTHER_NAMES
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	private String otherNames;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.NIC
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	private String nic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.ADDRESS
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	private Integer address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.DOB
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	private Date dob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.GENDER
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.TELEPHONE
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	private Integer telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.SCHOOL
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	private String school;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.C_ID
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	private Integer cId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.ID
	 * @return  the value of student.ID
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.ID
	 * @param id  the value for student.ID
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.FNAME
	 * @return  the value of student.FNAME
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public String getFname() {
		return fname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.FNAME
	 * @param fname  the value for student.FNAME
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public void setFname(String fname) {
		this.fname = fname == null ? null : fname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.LNAME
	 * @return  the value of student.LNAME
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public String getLname() {
		return lname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.LNAME
	 * @param lname  the value for student.LNAME
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public void setLname(String lname) {
		this.lname = lname == null ? null : lname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.OTHER_NAMES
	 * @return  the value of student.OTHER_NAMES
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public String getOtherNames() {
		return otherNames;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.OTHER_NAMES
	 * @param otherNames  the value for student.OTHER_NAMES
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public void setOtherNames(String otherNames) {
		this.otherNames = otherNames == null ? null : otherNames.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.NIC
	 * @return  the value of student.NIC
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public String getNic() {
		return nic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.NIC
	 * @param nic  the value for student.NIC
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public void setNic(String nic) {
		this.nic = nic == null ? null : nic.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.ADDRESS
	 * @return  the value of student.ADDRESS
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public Integer getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.ADDRESS
	 * @param address  the value for student.ADDRESS
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public void setAddress(Integer address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.DOB
	 * @return  the value of student.DOB
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public Date getDob() {
		return dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.DOB
	 * @param dob  the value for student.DOB
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public void setDob(Date dob) {
		this.dob = dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.GENDER
	 * @return  the value of student.GENDER
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.GENDER
	 * @param gender  the value for student.GENDER
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public void setGender(String gender) {
		this.gender = gender == null ? null : gender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.TELEPHONE
	 * @return  the value of student.TELEPHONE
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public Integer getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.TELEPHONE
	 * @param telephone  the value for student.TELEPHONE
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public void setTelephone(Integer telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.SCHOOL
	 * @return  the value of student.SCHOOL
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.SCHOOL
	 * @param school  the value for student.SCHOOL
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public void setSchool(String school) {
		this.school = school == null ? null : school.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.C_ID
	 * @return  the value of student.C_ID
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public Integer getcId() {
		return cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.C_ID
	 * @param cId  the value for student.C_ID
	 * @mbg.generated  Mon Jun 19 12:53:52 IST 2017
	 */
	public void setcId(Integer cId) {
		this.cId = cId;
	}
}